##
#Plugin: BankAccount
#Author: TAT
#CONFIGURATION
##

##
#Config: UseMySQL
#Example: true = MySQL // false = SQLite (flatfile)
##
UseMySQL: false

##
#Config: Transactions
#Doing: Save transactions in table
#Example: true = activate // false = deactivate
##
Transactions: true

##
#Informations to your MySQL connection
#Only if you're using MySQL (Set in UseMySQL)
##
MySQL-info:
    Host: localhost
    Port: 3306
    User: root
    Pass: password
    Database: minecraft

##
#Config: SQL-account-table / SQL-area-table
#Doing: Names of account and area table
##
SQL-account-table: bankaccounts
SQL-area-table: bankareas
SQL-loan-table: bankloans
SQL-transaction-table: banktransactions

##
#Config: UseOP / UsePermissions
#Doing: Use OP, Permissions and/or GroupManager(FakePermissions) to get admins
#Example: true = activate // false = deactivate
##
UseOP: true
UsePermissions: false
UseGroupManager: false

##
#Config: SuperAdmins
#Doing: Give the admins power to access all accounts?
#Example: true = activate // false = deactivate
##
SuperAdmins: true

##
#Config: Global
#Doing: Is it possible to use commands global or in specific areas?
#Example: true = global // false = specific areas
##
Global: true

##
#Config: AreaWandId
#Doing: Item ID to selection of areas
#Example: 339 = Paper
##
AreaWandId: 339

##
#Interest settings
#Time is in minutes
#Amount is % of account balance added to every account
##
Interest:
    Time: 5
    Amount: 0.1

##
#Loan settings
#Active: true = activate // false = deactivate
#Fixed-rate: 0 = no fixed rate // > 0 = fixed rate set to value
#Rate: Variable rates (only if fixed-rate is set to zero)
#Max-amount: 0.00 = No limit // > 0.00 = Highest amount that can be borrowed at a time (Note: only 1 loan at a time)
##
Loan:
    Active: false
    Fixed-rate: 0.00
    Rate:
        50: 0.1
        100: 0.3
        200: 0.5
    Max-amount: 200